services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17-alpine"
    env_file:
      - ../../.env.development
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
