services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../../.env.development
    environment:
      PGTZ: "UTC"
    ports:
      - 5432:5432
